RedHatInsights/topological_inventory-core

app/models/container_group.rb
app/models/container_node.rb
app/models/source.rb
db/migrate/20181011164429_add_container_nodes.rb
db/migrate/20181011172858_add_source_created_and_deleted_at_timestamps.rb
lib/topological_inventory/schema/default.rb

This adds the ContainerNodes model with a reference to ContainerGroups, and also adds source_created_at and source_deleted_at attributes to all container/service models.
There was already a deleted_at which is what we had in MIQ but since it is coming from the source data I thought it would be better to keep it consistent with source_created_at (MIQ calls this ems_created_on).

Add ContainerNodes and source_created_at/source_deleted_at

---

app/models/source.rb

When creating the default endpoint set the same tenant as its source.

Create the default endpoint with a tenant

---

app/models/container_template.rb
db/migrate/20181015150921_add_missing_name_to_container_template.rb

The ContainerTemplate model was missing a belongs_to container_project
and the table was missing the name column

Add missing properties to ContainerTemplate

---

lib/topological_inventory/schema/default.rb

Currently `:strategy` is not set and lazy_links are not found.
cc @agrare @Ladas

Setting default find strategy to :local_db_find_missing_references

---

bin/console

Forgot to update the require on bin/console when ar_helper was moved
from lib to lib/topological_inventory/persister in https://github.com/ManageIQ/topological_inventory-core/pull/26

Fix ArHelper require in bin/console

---

lib/topological_inventory/persister/worker.rb
spec/persister/worker_spec.rb

Use subscribe_messages so that inventory is only delivered to a single
persister worker.
Originally the kafka backend for manageiq-messaging had only
publish/subscribe_topic but now it supports queue type methods.
Merge together with: https://github.com/ManageIQ/topological_inventory-ingress_api/pull/4

Support parallel persisters with subscribe_message

---

db/schema.rb

It looks like both service_parameters_sets and service_plans made it into db/schema from a bad rebase.

Fix db/schema from a bad rebase

---

Gemfile
topological_inventory-core.gemspec

```
LoadError: cannot load such file -- acts-as-taggable-on
/home/bdunne/.gem/ruby/2.4.3/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `require'
/home/bdunne/.gem/ruby/2.4.3/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `block in require'
/home/bdunne/.gem/ruby/2.4.3/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:256:in `block in load_dependency'
/home/bdunne/.gem/ruby/2.4.3/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:662:in `new_constants_in'
/home/bdunne/.gem/ruby/2.4.3/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:256:in `load_dependency'
/home/bdunne/.gem/ruby/2.4.3/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `require'
/home/bdunne/.gem/ruby/2.4.3/bundler/gems/topological_invento …
```

TopologicalInventory::Api was failing to load due to missing gem

---

app/models/source.rb
app/models/source_type.rb
db/migrate/20181024163850_add_source_type.rb
db/schema.rb
spec/persister/worker_spec.rb
spec/tagging/tagging_spec.rb

Rather than have a string column for the source type and a pre-defined list of known types, add a table so that source types can be added dynamically along with the json schema for the create/update forms.  Then we can seed the builtin source types like openshift/aws/etc...

Add a SourceType model for dynamic provider types

---

db/migrate/20181113145803_add_indexes_on_name_column_to_node_and_namespace.rb
db/schema.rb

We are using name for secondary index, so we need db index to
speedup the lookup.

Add name indexes to node and namespace

---

app/models/orchestration_stack.rb
app/models/source.rb
app/models/tenant.rb
app/models/vm.rb
db/migrate/20181113182615_add_vms_table.rb
db/migrate/20181113190507_add_orchestration_stacks.rb
db/schema.rb

Adds models for Vms and OrchestrationStacks for AWS inventory.
I left out a `:template` from the vms table with the theory that we'll have separate tables for vms and templates.

Add VMs and OrchestrationStacks for AWS refresh

---

app/models/vm.rb

Allow vm#orchestration_stack to be null matching the database schema.

Vm#orchestration_stack is an optional parameter

---

lib/topological_inventory/core/ar_helper.rb

This is needed by things that will use this repo as a dependency since
the database.yml will not live in the gem directory.  Thus, the caller
can specify their own database.yml path.  An example usage from
topological_inventory-persister would be:
```ruby
require "topological_inventory/core/ar_helper"
TopologicalInventory::Core::ArHelper.database_yaml_path = Pathname.new(__dir__).join("config/database.yml")
TopologicalInventory::Core::ArHelper.load_environment!
```
e665c25
@agrare Please review.

Allow externally setting database yaml path

---

db/migrate/20181129150215_rename_archived_on.rb
db/schema.rb

All other timestamps are _at (e.g. created_at), rename archived_on for
consistency.
Depends on: https://github.com/ManageIQ/inventory_refresh/pull/51

Rename archived_on to archived_at for consistency

---

app/models/concerns/archived_concern.rb

Missed a couple of archived_on references renamed in
https://github.com/ManageIQ/topological_inventory-core/pull/72

Fix a couple last references to archived_on

---

lib/topological_inventory/core/ar_helper.rb

Fix for the errors in https://github.com/ManageIQ/topological_inventory-core/pull/76 where acts_as_tenant checking inflections on first require before other models are required

Set autoload_paths for core models and concerns

---

app/models/tenant.rb

Controllers will use this to decide whether the current tenant should be set to enforce tenancy

Add method for checking whether tenancy is enabled

---

app/models/container_group_tag.rb
app/models/container_image_tag.rb
app/models/container_node_tag.rb
app/models/container_project_tag.rb
app/models/container_template_tag.rb
app/models/service_offering_tag.rb

`belongs_to :source`s were added here https://github.com/ManageIQ/topological_inventory-core/pull/83.
Tables `XXX_tags` are for establishing M:N relations between `XXXs` and `tags` table but they don't need relation to `sources` table.
cc @gtanzillo 
@miq-bot assign @Ladas

Remove belongs_to :source from tag tables

---

app/models/vm.rb
lib/topological_inventory/schema/default.rb

Without defining the right strategy, the ICs are failing to archive entities.

Define retention strategy destroy for non archivable

---

app/models/availability.rb
app/models/source.rb
app/models/source_type.rb
db/migrate/20190208143909_add_availabilities_table.rb
db/schema.rb

Add a table to track the support and availability of features of resources/actions based on API path.
```
>> openshift_source = Source.create!(:tenant => tenant, :source_type => openshift_source_type, :name => "OCP", :uid => SecureRandom.uuid)
>> openshift_source.availabilities.create!(:action => "GET", :identifier => "/service_instances", :availability => "available", :last_valid_at => Time.now.utc, :last_checked_at => Time.now.utc)
>> openshift_source.availabilities.create!(:action => "GET", :identifier => "/service_offerings", :availability => "available", :last_valid_at => Time.now.utc, :last_checked_at => Time.now.utc)
>> openshift_source.availabilities.create!(:action => "GET", :identifier => "/service_plans", :availability => "available", :last_valid_at => Time.now.utc, …
```

Modeling features availabilities

---

db/seeds.rb

Add source type schemas for OpenShift and Amazon. These are in turn used to render the "Add a New Source" form in https://github.com/ManageIQ/topological_inventory-ui.
To be used together with https://github.com/ManageIQ/topological_inventory-ui/pull/17 and https://github.com/ManageIQ/topological_inventory-ui/pull/20
Seeding the JSON columns with a ruby hash, comes out of the API as a JSON object. :+1: 
~~Seeding the JSON column as a string, comes out of the API as a string.~~

Add source type schemas for OpenShift and Amazon.

---

app/models/container_group_tag.rb
app/models/container_image_tag.rb
app/models/container_node_tag.rb
app/models/container_project_tag.rb
app/models/container_template_tag.rb
app/models/service_offering_tag.rb
app/models/vm_tag.rb

Those references require `tenant_id` columns in tag models (e.g. `ContainerImageTag,...`) and those columns have  been removed in https://github.com/ManageIQ/topological_inventory-core/pull/109/commits/f2fd6e18569196b02a48f97bf2fea027dda50897.
cc @Ladas @agrare

Remove tenant reference from tag models

---

app/models/application_record.rb
lib/topological_inventory/core/logging.rb

The API clients initial configuration looks to see if Rails constant is defined and if it is will use Rails.logger.  Since we hack Rails::VERSION but do not set Rails.logger this causes any OpenAPI clients to throw an exception on initial configuration:
```
Traceback (most recent call last):
4: from bin/sources-sync:33:in `<main>'
3: from /home/agrare/.gem/bundler/gems/sources-api-client-ruby-632713f8cc89/lib/sources-api-client.rb:48:in `configure'
2: from /home/agrare/.gem/bundler/gems/sources-api-client-ruby-632713f8cc89/lib/sources-api-client/configuration.rb:153:in `default'
1: from /home/agrare/.gem/bundler/gems/sources-api-client-ruby-632713f8cc89/lib/sources-api-client/configuration.rb:153:in `new'
/home/agrare/.gem/bundler/gems/sources-api-client-ruby-632713f8cc89/lib/sources-api-c …
```

Fix issues with api clients looking for Rails.logger

---

db/seeds.rb

The `role` value is needed when creating `Endpoint` instances. Until recently this has beed hard-wired in the client.

Add "role" to source_type seeds.

---

app/models/tenant.rb

This was breaking the as_json handling in -api because it prepended
OpenApi::Serializer to ApplicationRecord.

Tenant needs to inherit from ApplicationRecord

---

lib/topological_inventory/schema/default.rb

It was removed in inventory_refresh
Depends on:

Remove saver_strategy option

---

app/models/tenant.rb

The tenant reference was removed from the join tables, and endpoints
were moved to the sources-api service.

Remove wrong tenant associations

---

app/models/volume.rb
app/models/volume_attachment.rb
app/models/volume_type.rb

Some models had a tenant_id but did not include the acts_as_tenant mixin so they were not being filtered by the API

Add missing acts_as_tenant_on to volume models

---

lib/topological_inventory/core/ar_helper.rb

Previously...
```
$ rake
app/models/source.rb:67: warning: already initialized constant Source::ALLOWED_REFRESH_STATUS_VALUES
app/models/source.rb:67: warning: previous definition of ALLOWED_REFRESH_STATUS_VALUES was here
```

Prevent re-requiring models leading to warnings in test

---

app/models/application_record.rb
topological_inventory-core.gemspec

Now that acts_as_tenant has released the gem with our fix we don't need
this hack anymore.

Remove the Rails hack needed for acts_as_tenant

---

app/models/source.rb

The datastore_mounts relation was defined through :hosts before the
hosts relation was defined.

Fix the Source.datastore_mounts through relation

---

app/models/service_instance.rb
app/models/service_instance_node.rb
app/models/service_offering.rb
app/models/service_offering_node.rb

Most belongs_to relations are optional in the database but default to
required with the newer version of rails.

Fix optional belongs_to

---

app/models/tag.rb
spec/models/tag_spec.rb

Add more test cases and ensure that tags from `#to_tag_string` can be parsed by `.parse` (with and without a namespace)

Tags without namespaces

---

app/models/network.rb
app/models/security_group.rb

Added missing associations 1:N between Security Group and Network.
Needed for openapi generator (resp. `rake openapi:generate` in topological-inventory-persister)

Security Group-Network association

---

app/models/cluster_tag.rb
app/models/concerns/act_as_taggable_on.rb
app/models/container_group_tag.rb
app/models/container_image_tag.rb
app/models/container_node_tag.rb
app/models/container_project_tag.rb
app/models/container_template_tag.rb
app/models/datastore_tag.rb
app/models/host_tag.rb
app/models/ipaddress_tag.rb
app/models/network_adapter_tag.rb
app/models/network_tag.rb
app/models/reservation_tag.rb
app/models/security_group_tag.rb
app/models/service_inventory_tag.rb
app/models/service_offering_tag.rb
app/models/subnet_tag.rb
app/models/vm_tag.rb
db/migrate/20200122181811_add_tenant_to_join_tables.rb
db/schema.rb

Previously querying the join table based on tag attributes wasn't working when tenancy was enabled.  The query was incorrectly using a different id as the tenant_id in a select.
Specifically see $1 in this line:
```sql
SELECT COUNT(*) FROM "container_node_tags" WHERE ((SELECT "tags"."namespace" FROM "tags" WHERE "tags"."tenant_id" = $1 AND "tags"."id" = "container_node_tags"."tag_id") = 'test') AND "container_node_tags"."container_node_id" = $1  [["container_node_id", 1174]]
```
From:
```
[----] D, [2020-01-21T16:56:01.518858 #163322:11a4608] DEBUG -- :   Tenant Load (0.2ms)  SELECT  "tenants".* FROM "tenants" WHERE "tenants"."external_tenant" = $1 LIMIT $2  [["external_tenant", "177"], ["LIMIT", 1]]
[----] D, [2020-01-21T16:56:01.520881 #163322:11a4608] DEBUG -- :   ContainerNode Load …
```

Add reference to tenant in the tag join classes

---

lib/topological_inventory/schema/default.rb

Reference to `tenant_it` have been added
https://github.com/RedHatInsights/topological_inventory-core/pull/165
so we need to populate them.
cc @bdunne

Fill tenant_id in tag join tables

---

app/models/source.rb

fix related to https://github.com/RedHatInsights/topological_inventory-core/issues/168
@miq-bot assign @slemrmartin

Add missing relation for ServiceInstanceNodeCredentials on Source model

---

app/models/source_region.rb
app/models/subscription.rb
app/models/tenant.rb

The belongs_to is already there on the other side.  Found while looking into the has many through subcollection issue.

Add missing has_many relations for ipaddresses

---

db/migrate/20200317082640_add_tracking_timestamps_to_refresh_state.rb
db/schema.rb
lib/topological_inventory/schema/base.rb
topological_inventory-core.gemspec

**Issue**: https://github.com/RedHatInsights/topological_inventory-persister/issues/52
Adding two timestamps to `RefreshState` model:
- **started_at** - Time of the beginning of collecting one data set [collector part]
- **finished_at** - Time after saving all parts of one data set [persister part]
Note: Linking data to refresh_state_part moved to persister (https://github.com/RedHatInsights/topological_inventory-persister/pull/53)
---

Refresh Tracking Timestamps

---

app/models/source.rb
app/models/task.rb
db/migrate/20200403114310_add_target_and_source_to_task.rb
db/migrate/20200403114310_add_target_to_task.rb
db/migrate/20200414123737_extract_tasks_source_ref_from_context.rb
db/schema.rb
lib/topological_inventory/core/version.rb
lib/topological_inventory/schema/default.rb
topological_inventory-core.gemspec

**Issue**: https://github.com/RedHatInsights/topological_inventory-ansible_tower/issues/83
Updates _running_ `Tasks` of associated `ServiceInstances`.  
Feature is moved from topological_inventory-ansible_tower operations worker because there isn't timeout.
`Task` extended by `source_id`, `target_source_ref` and `target_type`(`== ServiceInstance`)
Uses custom_save_block for `InventoryCollection :service_instances`.
**Note**: This PR processes Task's status in ansible-tower's specific way. Solved in #188 
---
---
**Gem version _1.1.0_**

Updating Task in ServiceInstance custom_save_block

---

db/migrate/20200428090420_add_request_id_to_task.rb
db/schema.rb
lib/topological_inventory/core/version.rb
lib/topological_inventory/schema/default.rb

**Issue** https://github.com/RedHatInsights/topological_inventory-ansible_tower/issues/83
Updated tasks are saved to inventory collections for further processing by Persister's Workflow.
---
**dependent** https://github.com/RedHatInsights/topological_inventory-persister/pull/56
---
**Gem version: 1.1.2**

Saving updated tasks to IC

---

db/migrate/20200414123737_extract_tasks_source_ref_from_context.rb

Apparently theres some older data in the db (from like Sep 2019) that has the `context` column as strings, which would cause the migration on API to blow up.
This handles that so the migrations can continue!
cc @syncrou @slemrmartin @gmcculloug

Add check to 4/14 migration to handle legacy string context

---

CHANGELOG.md

We attempted to test this but it was looking for tags that didn't exist at the time, this is just putting it in the right format.

Update changelog links to use compare instead of tag

---

db/migrate/20200505101547_add_forwardable_headers_remove_request_id_on_task.rb
db/schema.rb
lib/topological_inventory/core/version.rb
lib/topological_inventory/schema/default.rb

**Issue** https://github.com/RedHatInsights/topological_inventory-persister/issues/58
`Insights::API::Common::Request.current_forwardable` is saved in Task instead of x-rh-insights-request-id. To be able to resend it through Kafka in persister
---
**dependent** https://github.com/RedHatInsights/topological_inventory-persister/pull/59
**dependent** https://github.com/RedHatInsights/topological_inventory-api/pull/302
---
**Gem version: 1.1.4**

Store whole forwardable_headers in Task

---

db/migrate/20200421141934_add_source_updated_at.rb
db/schema.rb
lib/topological_inventory/core/version.rb

Adding DB migration with extra column for the volumes table.
related PRs: 
* https://github.com/RedHatInsights/topological_inventory-ingress_api-client-ruby/pull/66
* https://github.com/RedHatInsights/topological_inventory-ingress_api/pull/91
* https://github.com/RedHatInsights/topological_inventory-api-client-ruby/pull/33
* https://github.com/RedHatInsights/topological_inventory-azure/pull/25
* https://github.com/RedHatInsights/topological_inventory-persister/pull/61
based on https://projects.engineering.redhat.com/browse/TPINVTRY-789

Adding the source_updated_at column for volumes table.

---

app/models/refresh_state.rb
app/models/refresh_state_part.rb

Adding the `acts_as_tenant` behaviour for RefreshState and RefreshStatePart models, since both of them inherit from the active_record and not from the application_record like rest of the models.

Adding the 'acts_as_tenant' for RefreshState and RefreshStatePart models

---

CHANGELOG.md
lib/topological_inventory/core/version.rb
topological_inventory-core.gemspec

- bump miq-messaging version for rdkafka changes
- Release version 1.2.0
Bumping the versioning requirement for 1.2.0, that way it requires v0.2.0 of miq-messaging to pull in the rdkafka changes.

bump miq messaging version

---

.rubocop.yml

Because of https://github.com/ManageIQ/guides/pull/443 rubocop rules were moved to another repo. 
So we are moving the file to our common repo.
---
[RHCLOUD-10237](https://issues.redhat.com/browse/RHCLOUD-10237)

Rubocop rules from insights-api-common

---

.codeclimate.yml
.yamllint
topological_inventory-core.gemspec

Because of https://github.com/ManageIQ/guides/pull/443 rubocop rules were moved to another repo. 
So we are moving the file to our common repo.
* extending #211
---
[RHCLOUD-10237](https://issues.redhat.com/browse/RHCLOUD-10237)

Rubocop rules from insights-api-common + yamllint

---

CHANGELOG.md

Since version 1.1.7 the compare links have to be in format `v'1.1.7'`
Maybe it was the auto deployer

Compare links changed since 1.1.7

---

db/migrate/20210119154616_add_index_to_refresh_state.rb

Topological-inventory-db-cleaner is using:
`RefreshState.where('updated_at <= ?', threshold).delete_all`
but the db index is missing so it takes ages 
I thought we solved this issue before...

Added missing index RefreshState:updated_at for DB cleaner
