Dockerfile, docker-assets/entrypoint, lib/tasks/deployment.rake, openshift_template.yaml, tools/openshift_teardown
The rails server process will now not start until the postgres
service is ready.
The rails secret key and encryption key are now created at template
launch and stored in a secret.
=> Create an openshift_template and improve the entrypoint

lib/topological_inventory/engine.rb
Add db/migrate paths in the engine to the app's path list
=> Fix issue with running db:migrate from main app

lib/topological_inventory/schema/default.rb
Add a method that encapsulates the defaults and simplifies adding the collections.
=> Refactor how the inventory collections are built

db/migrate/20181016141948_add_json_spec_to_parameters_sets.rb
This adds jsonb columns to store create and update json schemas for
service parameters sets.
=> Add Create/Update JSON Schema to Param Sets

lib/topological_inventory/schema/default.rb
Default the inventory item tenant to be the same as the source's tenant.
=> Set the inv tenant to the source's tenant

app/models/concerns/archived_concern.rb, app/models/container_group.rb, app/models/container_node.rb, app/models/container_project.rb, app/models/container_template.rb, app/models/service_instance.rb, app/models/service_offering.rb, app/models/service_parameters_set.rb, app/models/source.rb, db/migrate/20181018082155_add_archived_on_timestamp_to_all_models.rb, lib/topological_inventory/schema/default.rb
=> Enable archivation

app/models/service_instance.rb, app/models/service_offering.rb, app/models/service_plan.rb, app/models/source.rb, app/models/tenant.rb, db/migrate/20181018141423_rename_service_parameters_sets_to_service_plans.rb, lib/topological_inventory/schema/default.rb
Rename to a more intuitive name.
We need to also update the api, ingress_api, ingress_api-client-ruby, and openshift-collectors.
Dependent:
=> Rename ServiceParametersSets to ServicePlans

Rakefile, db/schema.rb
We are missing db configuration and the schema wasn't modified
=> Fix db config for ci

Gemfile
and override_gem support
cc @agrare @Ladas @bdunne
=> Support for Gemfile.dev.rb

Gemfile, app/models/concerns/password_concern.rb
This should be just a temporary solution, since this service
should not be handling any passwords soon.
=> Drop dependency to gems pending and bring in the MiqPassword

app/models/task.rb, app/models/tenant.rb, db/migrate/20181026182144_add_tasks_table.rb, db/schema.rb
Add a tasks model to keep track of long running async operations.
Dependent: https://github.com/ManageIQ/topological_inventory-api/pull/31
=> Add a tasks model to track running operations

Gemfile, app/models/application_record.rb, app/models/container_group.rb, app/models/container_node.rb, app/models/container_project.rb, app/models/container_template.rb, app/models/endpoint.rb, app/models/service_instance.rb, app/models/service_offering.rb, app/models/service_plan.rb, app/models/source.rb, app/models/task.rb, app/models/tenant.rb, bin/topological_inventory-persister, db/migrate/20181023213355_add_tags_and_taggings.rb, db/schema.rb, lib/topological_inventory/persister/worker.rb, spec/spec_helper.rb, spec/tagging/tagging_spec.rb
=> Add basic tagging functionality

.codeclimate.yml, .gitignore, .rubocop.yml, .rubocop_cc.yml, .rubocop_local.yml, .travis.yml, README.md, config/database.dev.yml, topological_inventory-core.gemspec
Prepare Travis, CodeClimate, and deployment
=> Prepare Travis, CodeClimate, and deployment

db/migrate/20181102141329_add_ssl_options_to_endpoints.rb, db/schema.rb
Add SSL information to endpoints useful for client connections
=> Add SSL Security Details to Endpoints

Rakefile
@agrare @bdunne Please review.
=> db:migrate goes through environment first, and needs AR prepared

app/models/refresh_state.rb, app/models/refresh_state_part.rb, app/models/source.rb, app/models/tenant.rb, db/migrate/20181114094606_add_last_seen_at_to_all_tables.rb, db/migrate/20181114115416_add_refresh_states_and_refresh_state_parts.rb, db/schema.rb
Add models for mark and sweep and for sweeping job, we are allowing to re-queue it, if all the parts of the refresh were not finished.
=> Add models for mark and sweep

app/models/flavor.rb, app/models/vm.rb, db/migrate/20181128101451_add_flavors.rb, db/schema.rb
=> Add flavor model

app/models/refresh_state.rb, lib/topological_inventory/persister/worker.rb, lib/topological_inventory/persister/workflow.rb, spec/persister/mark_and_sweep_spec.rb, spec/persister/test_inventory/mark_and_sweep/mark_part_1.json, spec/persister/test_inventory/mark_and_sweep/mark_part_2.json, spec/persister/test_inventory/mark_and_sweep/sweep_all.json, spec/persister/test_inventory/mark_and_sweep/sweep_container_groups.json
Mark and sweep control mechanism
Depends on:
=> Mark and sweep control mechanism

db/migrate/20181128141221_add_json_schema_to_source_types.rb, db/schema.rb
Add a json schema for the form for source creation.
=> Add json schema to source_types for source create

db/migrate/20181205142648_add_unique_constraint_to_source_uid.rb, db/schema.rb, spec/models/service_plan_spec.rb
The uid on sources must be present and unique.
=> Add unique and not-null constraints to source.uid

lib/topological_inventory/core/service_plan_client.rb, spec/topological_inventory/core/service_plan_client_spec.rb
This is to address https://github.com/ManageIQ/topological_inventory-core/issues/75.
It will also need [this API PR](https://github.com/ManageIQ/topological_inventory-api/pull/60)
@mkanoor Let me know if this is what you were thinking.
/cc @agrare
=> Rework parameters for sending namespace and service_parameters

app/models/application_record.rb, app/models/authentication.rb, app/models/container.rb, app/models/container_group.rb, app/models/container_image.rb, app/models/container_node.rb, app/models/container_project.rb, app/models/container_template.rb, app/models/endpoint.rb, app/models/flavor.rb, app/models/orchestration_stack.rb, app/models/refresh_state.rb, app/models/refresh_state_part.rb, app/models/service_instance.rb, app/models/service_offering.rb, app/models/service_plan.rb, app/models/source.rb, app/models/source_region.rb, app/models/subscription.rb, app/models/task.rb, app/models/vm.rb, topological_inventory-core.gemspec
Note - tenancy is only enforced when a current tenant is set. This will happen in the controller
=> Enforce tenancy in all models having tenant_id

topological_inventory-core.gemspec
~~Depends on: https://github.com/ManageIQ/inventory_refresh/pull/52~~
=> Bump to rails 5.2

Gemfile, topological_inventory-core.gemspec
Related to https://github.com/ManageIQ/topological_inventory-core/pull/69#discussion_r243097547
=> Add manageiq-password to gemspec

db/migrate/20190104213045_rename_authentication_userid_to_username.rb
Based on https://github.com/ManageIQ/topological_inventory-orchestrator/pull/1#discussion_r245418147
=> Rename Authentication#userid to #username

app/models/concerns/password_concern.rb, topological_inventory-core.gemspec
- loosen dependency on Rails
- Upgrade and loosen dependency on manageiq-password
=> Loosen dependencies

.gitignore, lib/topological_inventory/core/ar_helper.rb, lib/topological_inventory/core/service_catalog_client.rb, spec/spec_helper.rb
cc @gtanzillo this should give us what we're looking for to figure out if we're sending the right parameters when ordering a service
=> Log the payload when creating a service instance

app/models/service_offering.rb, app/models/service_offering_tag.rb, app/models/source.rb, app/models/tenant.rb, db/migrate/20190116164905_add_extra_metadata_and_tags_for_service_offerings.rb, db/schema.rb, lib/topological_inventory/schema/default.rb
=> Add tags and metadata columns to service offering

app/models/service_offering.rb, app/models/service_offering_icon.rb, app/models/source.rb, app/models/tenant.rb, db/migrate/20190118110059_add_service_offering_icons.rb, db/schema.rb, lib/topological_inventory/schema/default.rb
=> Add service offering icons

db/migrate/20190111083026_change_sources_source_type_to_not_null.rb, db/schema.rb, db/seeds.rb, spec/models/service_plan_spec.rb
Add default source type for amazon and also make source type NOT NULL
Depends on:
=> Source type for amazon

db/migrate/20190111163026_change_sources_name_to_not_null.rb, db/schema.rb
=> Source name should be not null

Gemfile, db/migrate/20190122131958_add_missing_foreign_key_constraint_to_tasks.rb, db/migrate/20190122133424_index_foreign_keys_in_authentications.rb, db/migrate/20190122133425_index_foreign_keys_in_container_groups.rb, db/migrate/20190122133426_index_foreign_keys_in_container_projects.rb, db/migrate/20190122133427_index_foreign_keys_in_container_templates.rb, db/migrate/20190122133428_index_foreign_keys_in_endpoints.rb, db/migrate/20190122133429_index_foreign_keys_in_service_instances.rb, db/migrate/20190122133430_index_foreign_keys_in_service_offerings.rb, db/migrate/20190122133431_index_foreign_keys_in_service_plans.rb, db/migrate/20190122133432_index_foreign_keys_in_sources.rb, db/migrate/20190122153645_remove_extraneous_indexes.rb, db/migrate/20190124140942_add_missing_indexes_for_last_seen_at.rb, db/migrate/20190124154742_add_missing_not_null_constraints_to_source_ref.rb, db/schema.rb, spec/models/service_plan_spec.rb, spec/topological_inventory/core/database_health.rb, topological_inventory-core.gemspec
=> Test schema health

db/migrate/20190205174227_add_version_to_sources.rb, db/schema.rb
Add a version string to sources
=> Add a version to sources

spec/topological_inventory/core/database_health_spec.rb
Without this, the spec is not running in the CI. Also adding more exceptions.
=> Add _spec to database_spec health name

app/models/concerns/act_as_taggable_on.rb, app/models/vm_tag.rb, db/migrate/20190218180413_move_tag_value_to_tags.rb, db/migrate/20190218203848_remove_extra_columns_from_tagging_join_tables.rb, db/migrate/20190228103842_add_unique_indexes_to_tag_mapping_tables.rb, db/schema.rb, lib/topological_inventory/schema/default.rb
enhancing https://github.com/ManageIQ/topological_inventory-core/pull/104 and adding missing stuff. Also making it reversible (we should add specs for this)
merge together with:
https://github.com/ManageIQ/topological_inventory-ingress_api/pull/30
https://github.com/ManageIQ/topological_inventory-ingress_api-client-ruby/pull/27
https://github.com/ManageIQ/topological_inventory-collector-openshift/pull/39
https://github.com/ManageIQ/topological_inventory-collector-amazon/pull/12
=> Move value to tags

app/models/tag.rb
Needed for specs to pass in https://github.com/ManageIQ/topological_inventory-api/pull/143
=> Add missing relation

app/models/task.rb
Task states and statuses should be limited to the following values:
state: pending, queued, running, completed
status: ok, warn, error
Related to: https://github.com/ManageIQ/topological_inventory-api/pull/148
=> Add validations to task state, status

db/seeds.rb
Support for ansible tower collector
cc @Ladas
=> Added AnsibleTower SourceType to seeds

db/seeds.rb
Set password field types for secrets.
=> Update source type seeds with password fields.

app/models/concerns/act_as_taggable_on.rb, spec/models/concerns/acts_as_taggable_on_spec.rb
this PR is adding those methods:
**instance methods:**
- tag_list
- tag_add
- is_tagged_with?
- tag_remove
**class methods:**
- tagged_with 
https://projects.engineering.redhat.com/browse/TPINVTRY-184
=> Add basic methods for tagging in ActsAsTaggableOn

db/migrate/20190313191654_add_application_type_display_name.rb, db/schema.rb, db/seeds.rb
Seed ApplicationTypes with an initial set of applications: catalog, cost management, and topological inventory.
=> Seed ApplicationTypes

lib/topological_inventory/schema/base.rb, lib/topological_inventory/schema/default.rb
=> Schema to_hash method

db/migrate/20190325115642_external_tenant_must_be_unique_and_not_null.rb, db/schema.rb, spec/models/authentication_spec.rb, spec/models/concerns/acts_as_taggable_on_spec.rb
Fixing specs in Persister: https://github.com/ManageIQ/topological_inventory-persister/pull/21
=> external_tenant must be not null and unique

app/models/cluster.rb, app/models/cluster_tag.rb, app/models/host.rb, app/models/host_tag.rb, app/models/source.rb, db/migrate/20190514164916_add_clusters.rb, db/migrate/20190514165841_add_hosts.rb, db/schema.rb, lib/topological_inventory/schema/default.rb, spec/topological_inventory/core/database_health_spec.rb
Add initial tables for hosts and clusters, needed to add vsphere and ovirt inventory.
=> Add Host and Cluster models

app/models/datastore.rb, app/models/datastore_mount.rb, app/models/datastore_tag.rb, app/models/host.rb, app/models/source.rb, app/models/tenant.rb, db/migrate/20190522170940_add_datastores.rb, db/migrate/20190522172440_add_datastore_mounts.rb, db/schema.rb, spec/topological_inventory/core/database_health_spec.rb
Add a datastore model to track virtual storage, and links between hosts and datastores (datastore_mounts).
=> Add Datastore Model

Gemfile, topological_inventory-core.gemspec
=> InventoryRefresh from Gemfile to gemspec

lib/topological_inventory/schema/base.rb
=> Schema class by name method

app/models/host.rb, app/models/host_network_adapter.rb, app/models/network_adapter.rb, app/models/source.rb, app/models/tenant.rb, app/models/vm.rb, app/models/vm_network_adapter.rb, db/migrate/20190724194551_add_network_adapters.rb, db/schema.rb, spec/topological_inventory/core/database_health_spec.rb
Add a table for network adapters so that we can keep track of NIC mac
addresses and ipaddresses
=> Add network_adapters table and models

app/models/service_inventory.rb
Following discussion in #153 there are `has_many` associations of service_inventory.
=> ServiceInventory :has_many associations

app/models/concerns/act_as_taggable_on.rb, spec/models/concerns/acts_as_taggable_on_spec.rb
=> Don't create a tag if exists in ActsAsTaggableOn#tag_add

app/models/tag.rb, spec/models/tag_spec.rb
For https://github.com/ManageIQ/topological_inventory-api/pull/259
=> Add Tag#to_tag_string and allow #tag on create!

topological_inventory-core.gemspec
=> Use inventory-refresh v0.3.2

app/models/service_credential.rb, app/models/service_instance.rb, app/models/service_instance_node.rb, app/models/service_offering.rb, app/models/service_offering_node.rb, db/migrate/20200213135429_remove_service_credential_references.rb
First PR of Collecting Service Credentials for Ansible Tower effort - tracking issue : https://github.com/RedHatInsights/topological_inventory-core/issues/168
@miq-bot assign @agrare 
cc @slemrmartin
=> Remove ServiceCredential relations

app/models/service_credential.rb, app/models/service_credential_type.rb, app/models/source.rb, db/migrate/20200213150314_create_service_credential_types.rb, db/migrate/20200213173958_add_service_credential_type_to_service_credentials.rb, lib/topological_inventory/schema/default.rb
second part of https://github.com/RedHatInsights/topological_inventory-core/issues/168 
@miq-bot assign @slemrmartin
=> Add table and model for Service Credential Type an tie it with ServiceCredential

app/models/service_instance.rb, app/models/service_instance_service_credential.rb, app/models/service_offering.rb, app/models/service_offering_service_credential.rb, app/models/source.rb, db/migrate/20200214183108_create_join_table_service_offering_service_credentials.rb, db/migrate/20200214183117_create_join_table_service_instance_service_credentials.rb, lib/topological_inventory/schema/default.rb
Point 3 from https://github.com/RedHatInsights/topological_inventory-core/issues/168
cc @agrare 
@miq-bot assign @slemrmartin
=> Add tables, models and credentials for Service[Offering|Instance]Credential

app/models/service_instance_node.rb, app/models/service_instance_node_service_credential.rb, app/models/service_offering_node.rb, app/models/service_offering_node_service_credential.rb, app/models/source.rb, db/migrate/20200218182928_create_join_table_service_offering_node_service_credentials.rb, db/migrate/20200218183046_create_join_table_service_instance_node_service_credentials.rb, lib/topological_inventory/schema/default.rb
point 6 from https://github.com/RedHatInsights/topological_inventory-core/issues/168
cc @slemrmartin
=> Add Service[Offering|Instance]Node tables and model

topological_inventory-core.gemspec
=> ManageIQ -> RedHatInsights in homepage gemspec

app/models/source_type.rb
`SourceType` [has been extracted](https://github.com/RedHatInsights/topological_inventory-core/pull/121) to source-api
=> Remove model SourceType

db/migrate/20200313124806_remove_extraneous_index_from_service_credential_join_tables.rb, db/schema.rb
Fixes spec
https://github.com/RedHatInsights/topological_inventory-core/blob/master/spec/topological_inventory/core/database_health_spec.rb#L22
Removed indexes to credentials (similar to tag join tables indexes)
=> Removed extraneous indexes

lib/topological_inventory/core/version.rb
=> Update to version 1.0.0

lib/topological_inventory/core/version.rb, lib/topological_inventory/schema/default.rb
**Issue** https://github.com/RedHatInsights/topological_inventory-ansible_tower/issues/83
Removing source-speficic code for updating Task's status
---
---
**Gem version: 1.1.1**
=> ServiceInstance's task status update

CHANGELOG.md
=> Release version 1.1.4

spec/spec_helper.rb, topological_inventory-core.gemspec
Updating the `gemspec` and `spec_helper` files.
=> Setting up CodeClimate - Coverage

CHANGELOG.md, lib/topological_inventory/core/version.rb
**Gem version: 1.1.5**
---
**Depends on**:
=> Changelog 1.1.5

CHANGELOG.md, lib/topological_inventory/core/version.rb
Upgrading the gem version and CHANGELOG file.
=> Changelog and gem version upgrade.

lib/topological_inventory/schema/default.rb
Exposing ServiceInstance.extra['artifacts'] to Task.context['artifacts'].
Also switched from ActiveRecord update to bulk SQL update (50 times faster on 1000 records)
---
[TPINVTRY-1079](https://issues.redhat.com/browse/TPINVTRY-1079)
=> Added artifacts to tasks IC and bulk sql update

lib/topological_inventory/schema/default.rb
Support for updating Tasks where Service Instaces were archived (it means Jobs were deleted on the Tower side)
---
- **dependent** https://github.com/RedHatInsights/topological_inventory-ansible_tower/pull/137
---
[RHCLOUD-9508](https://issues.redhat.com/browse/RHCLOUD-9508)
=> Finishing tasks with archived service_instance

CHANGELOG.md, lib/topological_inventory/core/version.rb
Gem version: 1.1.8
---
- **dependent** https://github.com/RedHatInsights/topological_inventory-persister/pull/72
=> Changelog 1.1.8

db/migrate/20210106143551_add_guest_info_to_vms.rb, db/schema.rb
https://issues.redhat.com/browse/RHCLOUD-10836
=> Add guest_info column to the Vms table.

CHANGELOG.md, lib/topological_inventory/core/version.rb
We have a github workflow that auto-publishes the gem for us when the `version.rb` file changes.
=> Release 1.2.1
